# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: The GAM Digital Archive Project
  es: El Proyecto del Archivo Digital del GAM 
description:
  en: Updates page for the GAM Digital Archive Project 
  es: PÃ¡gina de noticias sobre el Proyecto del Archivo Digital del GAM
index:
  en: index.html
  es: indice.html
feed:
  en: /feed.xml
  es: /fuente.xml
baseurl: "/gam-archive" # the subpath of your site, e.g. /blog
url: "http://ds.haverford.edu" # the base hostname & protocol for your site
twitter_username: galarzaalex

# Build settings
markdown: kramdown
